### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by awakebrasil** [crankycyclops/DiscountCodeUrl#1]
Hello,
I can't get it to work

what to insert in the URL Parameter field?

Thank you

![01010101](https://user-images.githubusercontent.com/56883395/83064615-6ae18a00-a038-11ea-9dcb-e02d5238a87a.JPG)

**Comment by crankycyclops** [comment]
If you're using a query string, then this is the parameter that will have the coupon code. So, for example, if you want ?coupon=MYCOUPON at the end of the URL to apply that discount code, then set that value to "coupon".

**Comment by crankycyclops** [comment]
I haven't seen any further activity on this issue, so I'll go ahead and close it. If you're still experiencing problems, let me know.
