### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by norgeindian** [crankycyclops/DiscountCodeUrl#14]
It would be awesome if this module would also support PHP 8.

**Comment by crankycyclops** [comment]
I would love to, but unfortunately, I haven't been able to work on this for a while and it's effectively unmaintained. If you want to submit a PR, though, I'd be happy to merge it in :)

**Comment by norgeindian** [comment]
@crankycyclops , I tested locally, ran phpcs checks for compatibility and tested on my own.
It seems to be compatible already, so I simply adapted the requirement in the `composer.json`.
If anything comes up during the usage, I will be happy to provide a fix.
So if that is okay for you, it would be awesome, if you could merge my PR and publish a new version.

**Comment by crankycyclops** [comment]
Looks good. Merged. Thank you!

**Comment by norgeindian** [comment]
@crankycyclops , could you please publish a new release, so I can require the module with the changes?

**Comment by crankycyclops** [comment]
> @crankycyclops , could you please publish a new release, so I can require the module with the changes?

Done. Thanks again.

**Comment by norgeindian** [comment]
@crankycyclops , awesome, thanks a lot.
