### ISSUE TITLE
Any plans to check for PHP 7.4?

### ISSUE THREAD

**Issue by TerrapinSoftware** [crankycyclops/DiscountCodeUrl#8]
Do you plan to check for PHP 7.4 compatibility? Magento 2.4 wants PHP 7.4.

**Comment by crankycyclops** [comment]
I haven't tested with the latest version of Magento or PHP 7.4 yet, but it should work. I've enabled 7.4 in the develop branch's composer.json. Give it a go, and if it works, I'll merge that change into master.

**Comment by TerrapinSoftware** [comment]
Thank you - checking now with 2.4.0-p1. I'll keep you posted.

**Comment by TerrapinSoftware** [comment]
Just a follow-up. It seems to work just fine for Magento 2.4.0-p1, but did not test the URL path feature.

**Comment by crankycyclops** [comment]
Awesome. I'll merge this change to master so it's available to others. Thanks for testing.
